global:
  scrape_interval: 2s
  evaluation_interval: 15s

# ── Point Prometheus to Alertmanager ──
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# ── Load alert rules file ──
rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['localhost:5000']
